---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: titanic
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sassy19a/titanic-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: backend_url
              value: http://backend-svc.titanic.svc.cluster.local:8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-alb
  namespace: titanic
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
