---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: titanic
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: sassy19a/titanic-model
          imagePullPolicy: Always
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  namespace: titanic
  name: model-svc
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
